feat(storage): add smt and relational storage
axonweb3/spark pull request #8
Opened 2023-05-04 05:05 UTC by peterzhb

This PR adds the smt and relational storage (sqlite) to the spark.

2023-05-04 07:57 UTC, KaoImin requested changes

2023-05-04 07:57 UTC, KaoImin commented on storage/Cargo.toml
> +sea-orm = { version = "0.11", features = ["runtime-tokio-rustls", "sqlx-sqlite", "macros"], default-features = false }
We always use `native_tls` feature, because of the `rustls`  has some problem in cross-platform.

2023-05-04 07:57 UTC, KaoImin commented on storage/Cargo.toml
> +smt-rocksdb-store = { git = "https://github.com/axonweb3/smt-rocksdb-store.git", rev = "ebd58d4524113eb76b1f4d82ec2c59a0eaba39ab" }
```suggestion
smt-rocksdb-store = { git = "https://github.com/axonweb3/smt-rocksdb-store.git", rev = "ebd58d4" }
```

2023-05-04 07:57 UTC, KaoImin commented on storage/src/relation_db/mod.rs
> +        println!(
Use `log` instead of `println!`.

2023-05-04 07:57 UTC, KaoImin commented on storage/src/relation_db/mod.rs
> +use crate::types::smt::Address;
The order of imports should follow our development lint.

2023-05-04 07:57 UTC, KaoImin commented on storage/src/relation_db/mod.rs
> +}
Because of the return type is `Result`, should not use `expect` here.

2023-05-04 07:57 UTC, KaoImin commented on storage/src/smt/mod.rs
> +    types::smt::*,
The usage of Kleene star is forbidden expect after `prelude`.

2023-05-04 07:57 UTC, KaoImin commented on storage/src/smt/mod.rs
> +        let cf = self.db.cf_handle(&format!("{}_{}", table, "leaf")).unwrap();
```rust
format!("{}_{}", table, "leaf")
```

Should be refactor like this:

```rust
use derive_more::Display;

#[derive(Clone, Debug, Disply)]
pub enum NodeType {
	#[display(fmt = "branch")]
	Branch,
	#[display(fmt = "leaf")]
	Leaf,
}

fn cf_name(table: &str, node_type: Node_type) -> String {
    format!("{}_{}", table, node_type.to_string())
}
```

2023-05-04 07:57 UTC, KaoImin commented on storage/src/smt/mod.rs
> +            .filter_map(|(k, v)| {
```suggestion
            .into_iter()
            .filter_map(|(k, v)| {
```

2023-05-04 07:57 UTC, KaoImin commented on storage/src/smt/mod.rs
> +                if key_len != key_len {
This will always return true.

2023-05-04 07:57 UTC, KaoImin commented on storage/src/smt/mod.rs
> +        Ok(hash_map)
```suggestion
            .collect::<HashMap<(Staker, Amount)>>();

        Ok(kvs)
```

2023-05-04 07:57 UTC, KaoImin commented on storage/src/smt/mod.rs
> +        smt.update_all(kvs).expect("update_all error");
```suggestion
        smt.update_all(kvs)?;
```

2023-05-04 07:57 UTC, KaoImin commented on storage/src/smt/mod.rs
> +        let mut hash_map = HashMap::new();
```suggestion
        let mut hash_map = HashMap::with_capacity(epochs.len());
```

2023-05-04 07:57 UTC, KaoImin commented on storage/src/smt/mod.rs
> +            current_prefix.append(&mut staker_prefix.clone());
```suggestion
            let staker_prefix = SmtPrefixType::Address(staker).as_prefix();
            current_prefix.extend_from_slice(&staker_prefix);
```

2023-05-04 07:57 UTC, KaoImin commented on storage/src/smt/mod.rs
> +            top_prefix.append(&mut staker_prefix);
ditto

2023-05-04 07:57 UTC, KaoImin commented on storage/src/smt/mod.rs
> +        }
```suggestion
        delegators.iter().map(|(staker, addresses)| {
        	let val = addresses
                .into_iter()
                .map(|k| (k, Amount::default()))
                .collect::<Vec<_>>();
            (staker, val)
        }).collect::<HashMap<_, _>>();
```

2023-05-04 07:57 UTC, KaoImin commented on storage/src/smt/mod.rs
> +        delegators: HashMap<Staker, Vec<(Delegator, Amount)>>,
```suggestion
        delegators: Vec<Staker, Vec<(Delegator, Amount)>>,
```

The merge operation should be done in this function.

2023-05-04 07:57 UTC, KaoImin commented on storage/src/smt/mod.rs
> +        prefix.append(&mut SmtPrefixType::Address(staker).as_prefix());
This operation should be extract to a function, it is often used.

2023-05-04 07:57 UTC, KaoImin commented on storage/src/smt/mod.rs
> +        let mut hash_map = HashMap::new();
```suggestion
        let mut hash_map = HashMap::with_capacity(epoch.len());
```

2023-05-04 07:57 UTC, KaoImin commented on storage/src/smt/mod.rs
> +        let mut hash_map = HashMap::new();
ditto

2023-05-04 07:57 UTC, KaoImin commented on storage/src/smt/mod.rs
> +            .filter_map(|(k, v)| {
```suggestion
            .into_iter()
            .filter_map(|(k, v)| {
```

2023-05-04 07:57 UTC, KaoImin commented on storage/src/types/smt.rs
> +}
Why this enum exist?

2023-05-05 13:17 UTC, KaoImin commented on common/Cargo.toml
> +sea-orm = { version = "0.11", features = ["runtime-tokio-native-tls", "sqlx-sqlite", "macros"], default-features = false }
```suggestion
sea-orm = { version = "0.11", features = ["runtime-tokio-native-tls", "sqlx-sqlite", "macros"] }
```

2023-05-09 06:17 UTC, felicityin approved these changes

2023-05-09 07:33 UTC, merged